Repository CapstoneProjectKelompok3/NodeJS, pull requests merged in 2023-10, with the labels that each got.

#37 fix: docs users
  controllers/user-controller.js
  docs/swagger.json
  services/user/detail-service.js
  services/user/login-services.js
Labels: documentation

#39 Fix/user login
  docs/swagger.json
  services/user/login-services.js
Labels: enhancement

#42 feat(login): return id user when login success
  docs/swagger.json
  services/user/login-services.js
Labels: enhancement

#44 feat(api): rate limit 100 request per ip in 1 hour
  main.js
  package-lock.json
  package.json
Labels: enhancement

#52 style: remove unused comments
  services/user/updatePass-services.js
Labels: duplicate

#55 Feat/mailer
  .env example
  config/mailer.js
  package-lock.json
  package.json
  prisma/migrations/20231003051733_create_table_authentications/migration.sql
  prisma/migrations/20231003152115_delete_table_authentications/migration.sql
  prisma/migrations/20231003170802_add_table_email_activated/migration.sql
  prisma/schema.prisma
  repositories/mail.js
  repositories/user.js
  routers/api-router.js
  services/user/register-services.js
Labels: enhancement

#65 Fix/duplicate nik
  controllers/user-controller.js
  prisma/migrations/20231004155529_update_column_nik/migration.sql
  prisma/schema.prisma
  repositories/user.js
  services/user/register-services.js
Labels: bug

#67 testing: register user
  .babelrc
  jest.config.json
  main.js
  package-lock.json
  package.json
  server.js
  testing/user/register.test.js
Labels: testing

#70 Fix/migrations
  main.js
  prisma/migrations/20231003193834_/migration.sql
  prisma/migrations/20231003201033_/migration.sql
  prisma/migrations/20231005130718_create_table_message_and_room/migration.sql
  prisma/schema.prisma
Labels: bug

#72 Refactor: socket io event emitter for real time message
  .env example
  config/mongoose.js
  main.js
  server.js
  services/socket.io/adminMessage.js
  services/socket.io/userMessage.js
Labels: enhancement

#76 fix: cannot listen socket io
  main.js
  server.js
Labels: bug

#78 Feat/create emergencies
  helper/api/create-emergency.js
  helper/api/index.js
  middleware/verify-token.js
  services/message/newmessage-service.js
Labels: enhancement

#80 Refacfor: error response message
  .env example
  controllers/feedback-controller.js
  helper/api/get-emergency.js
  helper/api/index.js
  services/feedback/create-service.js
Labels: enhancement
